import { SignInButton, SignOutButton, useUser } from '@clerk/nextjs';
import styles from './index.module.css';
import Head from 'next/head';
import Link from 'next/link';
import { api } from '~/utils/api';

export default function Home() {
  const user = useUser();
  const { data } = api.businesses.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}

        <div>
          {data?.map((business) => (
            <div key={business.id}>{business.name}</div>
          ))}
        </div>
      </main>
    </>
  );
}
