import {
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
  useUser,
} from '@clerk/nextjs';
import styles from './index.module.css';
import Head from 'next/head';
import Link from 'next/link';
import { api } from '~/utils/api';
import type { RouterOutputs } from '~/utils/api';
import Image from 'next/image';

const AddBusinessWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div>
      <Image
        src={user.imageUrl}
        alt={`${user.firstName}'s profile image`}
        height={64}
        width={64}
      />
    </div>
  );
};

type BusinessWithUser = RouterOutputs['businesses']['getAll'][number];

const BusinessView = (props: BusinessWithUser) => {
  const { business } = props;

  return (
    <div key={business.id}>
      {business.name}
      {' • '}
      <a href={business.url} target="_blank" rel="noopener noreferrer">
        Website
      </a>
      {' • '}
      <a href={`tel:+${business.phone}`}>{business.phone}</a>
    </div>
  );
};

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.businesses.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <SignedIn>
            <AddBusinessWizard />
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>

          <div>
            {data.map((fullListing) => (
              <BusinessView key={fullListing.business.id} {...fullListing} />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
